### ISSUE TITLE
What append when there is no `index.html` file.

### ISSUE THREAD

**Issue by albandewilde** [ysugimoto/go-static-server#1]
When there is no `index.html` file, the web page tell us the file `index.html` is missing.

Is that possible, when that file is missing to serve the content of the current directory ?
In the same style as the comment `python -m http.server` will do it.

Thanks.

**Comment by jarmo** [comment]
Just in case you didn't notice, I've implemented this feature at https://github.com/ysugimoto/go-static-server/pull/3

**Comment by albandewilde** [comment]
Thanks, I just see it.
